services:
  postgresql:
    container_name: postgresql_container
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - batch_network
    volumes:
      - challenge_postgresql_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "9000:9000"  # API S3
      - "9001:9001"  # MinIO Web Console
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: admin12456
    command: server --console-address ":9001" /data
    volumes:
      - challenge_minio_data:/data
  # Include all the necessary settings to include a document management service in the stack
  # Remember to configure this service to limit the memory to 50MB
  # document-management-service:
  #    environment:
  #      - JAVA_OPTS=-Xmx50m -Xms50m
  #    deploy:
  #      resources:
  #        limits:
  #          memory: 50M

volumes:
  challenge_postgresql_data:
    driver: local
  challenge_minio_data:
    driver: local

networks:
  batch_network:
    driver: bridge
